### ISSUE TITLE
pointcloud_to_laserscan collides with the already released package.  

### ISSUE THREAD

**Issue by tfoote** [robotictang/eddiebot#1]
Please remove or rename this package as it masks the already released package in the flat package namespace. 

If you copy a package you need to rename it so as not to collide in the flat namespace.  A better solution is to simply add a dependency on the stack which the package is inside of.  

This holds true for many of your packages where it would be better to add a dependency on the code you copied and use the parameterization available to use it for your own uses.  Duplicating code leads to extra maintenance.  I expect a lot of the packages you copied from the turtlebot stacks can be done using just custom launch files in eddibot_bringup.

**Comment by robotictang** [comment]
Thanks for the tips and bug report. I had removed the pointcloud_to_laserscan folder in the eddiebot directory.

**Comment by robotictang** [comment]
Issue close.
